### ISSUE TITLE
plugin err dialog bug

### ISSUE THREAD

**Issue by fire2a** [fire2a/C2FSB#16]
#fire2A/C2FSB

**Comment by fdobad** [comment]
en requirements.txt sale el nombre "Pillow",
en el código se usa `import PIL`, pero estaba chequeando importar 'Pillow' por piensa que no existe PIL

**Comment by fdobad** [comment]
La solución final es agarrar cada distribution name de requirements.txt e ir online a pypi a buscar su import name... bastante overkill; como no hay paquete std que haga eso, mejor no meterle un requirement más a la lista. Así que siguiendo los consejos de stackoverflow:

AHORA HAY QUE MANTENER EL ARCHIVO requirements_import_names.txt 

Donde salen los import names, distintos de los distribution names que salen en requirements.txt

https://github.com/fdobad/fire2am-qgis-plugin/commit/ca965473431892afcd83b923dc9b8b515f5922b6

**Comment by RodrigoMahalufRecasens** [comment]
Añadir que pip install en caso de que el módulo no esté.

**Comment by fdobad** [comment]
Añadido acá https://github.com/fdobad/fire2am-qgis-plugin/commit/4640f14b9e71c2663f926f17418ccbe4c55efd0f
Explicado porque es malo acá https://github.com/fdobad/doctest/blob/main/docs/readme_dev.md#0-adding-new-packages
