### ISSUE TITLE
Revisar porqué está corrido Flame Length & Byram Intensity

### ISSUE THREAD

**Issue by fire2a** [fire2a/C2FSB#18]
![Image](https://user-images.githubusercontent.com/29801096/228432609-95ff5dfe-92d6-4bbd-93d7-eeee8e205a1a.png)

**Comment by RodrigoMahalufRecasens** [comment]
@DavidPalaciosM ¿puede ser que donde hay incendio no halla Flame Length? 
@fdobad volver a simular y mandar resultados a David. Mejor usar un incendio chico, ahí se nota más el desafase.

**Comment by fdobad** [comment]
actualizo, quitemos ROS

**Comment by RodrigoMahalufRecasens** [comment]
Fernando manda simulaciones mañana (17/05) 
David revisa simulación y ver qué pasó (17/05) 
Corregir el código si es que falló (18/05)

**Comment by fdobad** [comment]
mandado zip de una corrida a la derecha canal informática, discord (no creo que funque este link pero = https://cdn.discordapp.com/attachments/1057316985362456616/1108056146461339738/Instance23-05-16_11-35-20.zip )
@DavidPalaciosM

**Comment by fire2a** [comment]
Al final sí era que los estaba escribiendo corridos en un espacio: los guardaba en un vector en la posición i+1, pero tenía que guardarse en la posición i
