### ISSUE TITLE
Mod havaster_cells

### ISSUE THREAD

**Issue by fire2a** [fire2a/C2FSB#20]
# Modificar la opción "harvested cells" por "firebreacks" en el plugins.

**Comment by fire2a** [comment]
Modificar la opción "harvested cells" por "firebreacks" en el plugins.

**Comment by fire2a** [comment]
New flag: --FirebreakCells filename.csv

**Comment by fdobad** [comment]
Por mi lado cambiado acá https://github.com/fdobad/fire2am-qgis-plugin/commit/7550eaa81653e72f710367138c0ae2b14eaa6ea7

**Comment by RodrigoMahalufRecasens** [comment]
@DavidPalaciosM cambió más que esto. @fdobad acuerdate de compilar.
