### ISSUE TITLE
Modificar prints en python con flush = True

### ISSUE THREAD

**Issue by fdobad** [fire2a/C2FSB#4]
# rationale
Para comunicar al usuario gráfico en qué etapa va la ejecución del código (llamado desde `main.py`), se usan los prints a la consola.  
Pero para que el código no se atore imprimiendo cada print, se hace un buffered print que básicamente junta los prints en grupos y luego los imprime.  
Lamentablemente al llamar un proceso de python externo desde código (ej. `subprocess.Popen`) el grupo se acumula y se entrega al finalizar la ejecución, o después del código de error si hubo fallo
## objetivo : informar al usuario en tiempo real sobre la ejecución del código

# request
- Modificar o añadir ciertos prints fundamentales con el kwarg ´flush=True´ ojala 10?  
- Al menos uno al principio de todo que nunca falle y otro al final.

ejemplo:
```
print("------ Generating Statistics --------")
print("------ Generating Statistics --------", flush=True)
```

# mejoras futuras
añadir otros prints con un tag de % de ejecución
print("%%tag%% 0.5", flush=True)
así se puede mostrar un progress bar en la ventana run de la interfaz

# test de mentions
 @DaviPalaciosM

**Comment by fire2a** [comment]
Done

**Comment by fdobad** [comment]
funciona bien! gracias
