### ISSUE TITLE
Weathers con datetime no secuenciales por hora

### ISSUE THREAD

**Issue by fdobad** [fire2a/C2FSB#8]
Estoy usando el campo datetime de Weather.csv o el indicado por WeatherHistory.csv para animar los ForestGrids en QGIS al simular 1 incendio.

Para estos casos, si el datetime no varía 1 hora entre filas, el animador se pierde.
Por favor modificar los weathers para que todos varien su datetime entre filas ojala 1 hora entre cada uno.

**Comment by fire2a** [comment]
Los weathers vienen de un formato previo, no necesariamente variarán de a 1h

**Comment by fdobad** [comment]
Ok, lo voy a dejar consignado en el user manual
