### ISSUE TITLE
Flame length output added y modificacion de como se escriben los outputs

### ISSUE THREAD

**Issue by fire2a** [fire2a/C2FSB#9]
#Se modificó la bandera --out-behavior.

##Antes: 
Ponías --out-behavior y generaba intensity.asc para cada sim, ros.asc para cada sim y crown.asc para cada sim (esto último si es que pones --cros)

##Ahora:
Pones --out-ros y se genera ros.asc para cada sim, --out-fl y se genera fl.asc, --out-intensity y se genera intensity para cada sim y --out-crown y se genera crown.asc para cada sim si es que pones --cros

**Comment by fdobad** [comment]
Yo lo logré implementar! gracias
